# Generated by Django 5.0.6 on 2024-06-07 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 7, 3, 44, 35, 516795, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
